logo:
  #nav_mobile: images/logo-apollo-space-left.svg
  #subbrand: images/logo-apollo-subbrands-developers-space.svg
  src: '/images/logo-300.png'
  title: KepleJs Docs
  url: https://keplerjs.github.io/docs

favicon: images/favicon.ico

nav_links:
  'Website':
    url: https://keplerjs.github.io/
  'GitHub':
    url: https://github.com/Keplerjs
  'Blog':
    url: https://medium.com/@keplerjs
